### ISSUE TITLE
Conversion of makail's Item Drawers

### ISSUE THREAD

**Issue by PoseidonOil** [war3i4i/ItemDrawers#1]
Can Item Drawers in existing worlds / servers made using the ItemDrawers mod by makail (https://valheim.thunderstore.io/package/makail/ItemDrawers/) be converted to wood Item Drawers in this mod? I'd love a conversion added into this mod, but I'd be satisfied with a manual method of conversion.

Currently, when I switch from makail's now broken mod to this one, all of my existing item drawers disappear.

I like this mod, I'd love to switch to it, but I'm hoping to avoid the effort of loading an old version to empty all the makail ItemDrawers. Hoping a conversion is possible.

Thanks!

**Comment by war3i4i** [comment]
[e3cf63f](https://github.com/war3i4i/ItemDrawers/commit/e3cf63f8fd15a17548ad6a41d27531b789d5902c)

**Comment by war3i4i** [comment]
Just finished that and waiting for tests from my friend. If all good i'll release it

**Comment by war3i4i** [comment]
I've released new version on TS, give it a try and tell me if it works

**Comment by PoseidonOil** [comment]
It works! Thank you!

There's a minor issue with the location of the converted drawers - it seems like the face of your drawers is indexed to the midpoint or possibly the rear edge of makail's drawers. So after conversion, the drawers are all set back into (or through) the structure they were attached to originally. It's only a minor issue. Thanks for such a quick update!!
