### ISSUE TITLE
CraftFromContainers compatibility

### ISSUE THREAD

**Issue by ChrisGz95** [war3i4i/ItemDrawers#11]
No idea which mod is the true issue, but I figured it couldn't hurt to mention here.  The old mkz version of item drawers worked with the aedenthorn craft from containers.  Is there a setting in the mod we can enable to get it to cooperate or are we out of luck?

**Comment by war3i4i** [comment]
Use Azu Crafty Boxes mod. I've added this mod support into his

**Comment by WernerCD** [comment]
@war3i4i not sure if you'll see this but Craft FROM Containers does the FROM part... are there any Sort mods that do the TO part of dumping inventory into your very fancy drawers?
