### ISSUE TITLE
It seems that your item drawers don't marked as chests?

### ISSUE THREAD

**Issue by Dorennor** [war3i4i/ItemDrawers#12]
[Automatic Fuel](https://www.nexusmods.com/valheim/mods/2039)

This mod, which provides auto fuel functionality, doesn't work with your item drawers, before we used [Item Drawers](https://www.nexusmods.com/valheim/mods/854) and it worked correctly with Auto fuel, is it possible to add same functionality (i.e. working with auto fuel mods)?

**Comment by Dorennor** [comment]
Also it seems that ValheimPlus doesn't recognize them as chests, because on a working station I cant see any of my stored materials.

**Comment by Jysinn** [comment]
I second Dorennors comment about ValheimPlus. This mode would be perfect if you could mark them as chests internally so materials can be pulled automatically.

Thanks!

**Comment by war3i4i** [comment]
ItemDrawers are not containers (chests). And they won't be. In order to use Drawers for your purposes mod author can use API . I've added craft from container support and such to Azumatt's Crafty Boxes mod, use them

**Comment by Jysinn** [comment]
Azumatt's Crafty Boxes works perfect! THANKS!

**Comment by Dorennor** [comment]
Wrote to author of Auto Fuel but sadly that I can't use this functionality.
