### ISSUE TITLE
kg.itemdrawers is not installed on the server?

### ISSUE THREAD

**Issue by modsforall** [war3i4i/ItemDrawers#13]
Hi,

I was using the previous version of ItemDrawers by Makail.  Worked beutifully.

I disabled his version (did not uninstall, was worried about data loss), and installed your version.   However, Im getting this error message.

I host my own dedicated server on my PC.  And ideas?  Im also worried about losing all our items/resources making the switch.  How do I avoid this!!!?

Thanks!

**Comment by war3i4i** [comment]
I can't see error message

**Comment by war3i4i** [comment]
Mod should be also installed on serverside because of Config sync

**Comment by modsforall** [comment]
> Mod should be also installed on serverside because of Config sync

Which files do I install on the server?  Im just using your Thunderstore mod but dont know where the server files are.

Also, I was using Makails previous mod.  He DID NOT require any server side files.  Will this mod conflict with the data from his mod?  It seems very different if there are server side files.  Im terrified of losing all our resources.  We spending like 150 hours in game lol.  Thanks!

**Comment by modsforall** [comment]
> > Mod should be also installed on serverside because of Config sync
> 
> Which files do I install on the server? Im just using your Thunderstore mod but dont know where the server files are.
> 
> Also, I was using Makails previous mod. He DID NOT require any server side files.
> 
> Will this mod conflict with the data from his mod? It seems very different if there are server side files. Im terrified of losing all our resources. We've spent like 150 hours in game lol. Thanks!

SOS please help!  Thanks.

**Comment by modsforall** [comment]
> Mod should be also installed on serverside because of Config sync

Please help!  What files do I install on the server?  Thanks!

**Comment by modsforall** [comment]
Please someone help.  I cant play the game until I sort out this mod!  Thanks.

**Comment by war3i4i** [comment]
You install it same way as you install any mod on clientside. Just put BepInEx on serverside and put mods there
