### ISSUE TITLE
Any chance of making this compatible with Craft From Containers by Aedenthorn?

### ISSUE THREAD

**Issue by olavr-dev** [war3i4i/ItemDrawers#15]
I prefer this version of ItemDrawers to the one from makzimus, but unfortunately the "Craft Build Smelt Cook Fuel Pull From Containers" mod from Aedenthorn (https://www.nexusmods.com/valheim/mods/40) does not pull from any of the drawers.

Any chance of patching in a compatibility fix?

Thanks for your great work!

**Comment by Geethebluesky** [comment]
I have the same request, it seems like this is the most requested feature. I end up with so many drawers it's a real pain to have lost the ability to auto-store to all drawers automatically, auto-stack, and retrieve from drawers automatically when using nearby crafting stations.

**Comment by war3i4i** [comment]
Its something that other mod authors would need to do. If you want to use craft from containers just use AzuCraftyBoxes mod. I've added drawers mod support there
