### ISSUE TITLE
How do you install this mod on serverside???

### ISSUE THREAD

**Issue by modsforall** [war3i4i/ItemDrawers#16]
I still cant solve this issue.  Can someone please tell me where the server files are?  What directory do I save them in?

Will this version preserve my old Makail items in game?

Thanks.

**Comment by BobZilla-be** [comment]
Hello,
Jus copy kg_ItemDrawers.dll.mdb and kg_ItemDrawers.dll to /BepInEx/plugins

**Comment by war3i4i** [comment]
As @BobZilla-be said, just install it on serverside same way you do it on clientside. Install BepInEx and put mod in plugins folder
