### ISSUE TITLE
ItemDrawer hammer tab shows up, but is not selectable

### ISSUE THREAD

**Issue by azegoca** [war3i4i/ItemDrawers#19]
I am seeing this BepInEx error:
```
[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <17d9ce77f27a4bd2afb5ba32c9bea976>:0)
(wrapper dynamic-method) PieceTable.DMD<PieceTable::UpdateAvailable>(PieceTable,System.Collections.Generic.HashSet`1<string>,Player,bool,bool)
Player.UpdateAvailablePiecesList () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
(wrapper dynamic-method) Player.DMD<Player::SetPlaceMode>(Player,PieceTable)
Humanoid.SetupEquipment () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Humanoid.EquipItem (ItemDrop+ItemData item, System.Boolean triggerEquipEffects) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Player.EquipInventoryItems () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Player.Load (ZPackage pkg) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
PlayerProfile.LoadPlayerData (Player player) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
(wrapper dynamic-method) Game.DMD<Game::SpawnPlayer>(Game,UnityEngine.Vector3)
Game.UpdateRespawn (System.Single dt) (at <67f3c386e04446c49523ecfd5b8921c2>:0)
Game.FixedUpdate () (at <67f3c386e04446c49523ecfd5b8921c2>:0)
```
This is my testing mod set:

[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 7 plugins to load
[Info   :   BepInEx] Loading [AzuExtendedPlayerInventory 1.4.0]
[Info   :   BepInEx] Loading [Configuration Manager 18.3]
[Info   :   BepInEx] Loading [Jotunn 2.20.0]
[Info   :Jotunn.Main] Initializing ModCompatibility
[Info   :Jotunn.Main] Initializing SynchronizationManager
[Info   :Jotunn.Main] Initializing NetworkManager
[Info   :   BepInEx] Loading [kg.ItemDrawers 1.0.7]
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #5 - 'localization_ashlands' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #0 - 'localization' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #1 - 'localization_extra' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #2 - 'heightmap_message' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #3 - 'localization_hildir' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #4 - 'localization_emotes' language: 'English'
[Info   : Unity Log] 05/15/2024 15:26:24: Loaded localization file #5 - 'localization_ashlands' language: 'English'
[Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[Info   :   BepInEx] Loading [Server Devcommands 1.79]
[Info   :   BepInEx] Loading [World Edit Commands 1.60]
[Message:   BepInEx] Chainloader startup complete

![Screenshot 2024-05-15 153536](https://github.com/war3i4i/ItemDrawers/assets/29699691/627821e6-375b-4773-8e07-69dc5a008b42)

**Comment by war3i4i** [comment]
Fixed, sorry for delay was struggling with Rider license stuff
