### ISSUE TITLE
Compability with craft from containers mods

### ISSUE THREAD

**Issue by Bolgath** [war3i4i/ItemDrawers#2]
Hi thanks for the remake of that great mod. Just wonder if it's possible to get it to work with mods that you can craft direct from containers like AzuCraftyBoxes or Craft Build Smelt Cook Fuel Pull From Containers? I used the old mod before and it worked fine to craft from the itemdrawers and that was really a big time saver :)

**Comment by war3i4i** [comment]
Working on AzuCraftyBoxes fork atm

**Comment by war3i4i** [comment]
Added drawers support to AzuCraftyBoxes, waiting when he'll accept PR and release mod on TS
