### ISSUE TITLE
ItemDrawers seems not to work with any CraftFromContainers mod

### ISSUE THREAD

**Issue by Schorsch0815** [war3i4i/ItemDrawers#21]
Hi, I like the mod, as it seems to be a good successor of ItemDrawers mod by makzimus (https://next.nexusmods.com/profile/makzimus/mods?gameId=3667). But currently, yours seems not to support any CraftsFromContainer mods like (https://thunderstore.io/c/valheim/p/Buttergeland/CraftFromContainers/ or https://thunderstore.io/c/valheim/p/DrZed/CraftFromContainers/).
It would be cool if you could bring support for your ItemDrawers mod, as it was possible with the mod from makzimus in the good old days.
Thank you!

**Comment by war3i4i** [comment]
Use AzuCraftyBoxes

**Comment by Schorsch0815** [comment]
Thank you very much, works great! Sorry did not checked the closed issues, may be just add a hint in the description.
