### ISSUE TITLE
ItemDrawers does not work with new Bog Witch update 0.219.14

### ISSUE THREAD

**Issue by Schorsch0815** [war3i4i/ItemDrawers#24]
Obersvation:
No error in log during startup, but when a game is started, then

[Error  : Unity Log] MissingFieldException: Field not found: System.Collections.Generic.List`1<string> .Hud.m_buildCategoryNames Due to: Could not find field in class
Stack trace:
PieceManager.PiecePrefabManager.Hud_AwakeCreateTabs () (at C:/Stuff/RiderProjects/ItemDrawers/Managers/PieceManager.cs:1757)
(wrapper dynamic-method) Hud.DMD<Hud::Awake>(Hud)
UnityEngine.GameObject:SetActive(GameObject, Boolean)
SetActiveOnAwake:Awake()

After loading the game In the lower middle you see an overlay like:
![image](https://github.com/user-attachments/assets/570e5d0f-aea6-457c-945c-19bb57a4bb35)
and this will stay.

I would like to see this plugin fixed, as it is such a great easement.

**Comment by war3i4i** [comment]
1.0.9 updated
