### ISSUE TITLE
Upgrading from "old" itemdrawers

### ISSUE THREAD

**Issue by Onkl** [war3i4i/ItemDrawers#4]
Hi

I was using the old itemdrawers on my dedicated server for a while but that mod doesn't work anymore since the last update I tried to switch to your mod.

It works wonderful when I copy the world from my server to my local machine and start it on my gaming rig. It works with all the other mods (list below) active and everything is cool. All the items I stored in the old mods itemdrawers show up in the new ones from your mod.

But when I try to play the world on my dedicated server I get the following error message after I enter the password to join the server:

Incompatible version

kg.ItemDrawers is not installed on the server

![2023-12-25 07_45_19-Valheim](https://github.com/war3i4i/ItemDrawers/assets/20339471/90096c4b-66e5-4579-9b50-a1dc25998d10)

I run the following mods:

- EpicLoot
- NoRainDamage
- PlantEverything

and 

- kg_ItemDrawers

I tried the following:

- Recreated/repulled/updated the docker image of my valheim server (cm2network/valheim:latest)
- Deleted all mods and reinstalled them from zips
- Deactivated all the mods except kg_ItemDrawers
- Running the world (with all mods active) locally instead of on the server (works)
- Running the world on the server without kg_ItemDrawers (works)
- Running the world on the server with all mods active server side but not loading itemdrawers on the client

If there is anything you can think of that I could try I would be very glad!

Happy holidays!

**Comment by war3i4i** [comment]
ItemDrawers mod should also be on serverside since it enforces some of configs

**Comment by Onkl** [comment]
I do have it installed server side. But as soon as I have it active on the server AND on the client, I get the error message above.

**Comment by war3i4i** [comment]
Send logs from serverside

**Comment by Onkl** [comment]
[outputlog_server.txt](https://github.com/war3i4i/ItemDrawers/files/13764709/outputlog_server.txt)

**Comment by war3i4i** [comment]
Seems like you server doesn't run BepInEx at all so it doesn't load any mods

**Comment by Onkl** [comment]
Thank you, you are right. I don't know what and how I did that, but I will check how I'll get it running again.

**Comment by Onkl** [comment]
It works, thank you so much! Sorry for using you as tech support as this was totally unrelated to your mod. I wish you just the best and please keep up the good work.
