### ISSUE TITLE
when player's inventory is full, the next item that is retrieved is voided

### ISSUE THREAD

**Issue by howardxu23** [war3i4i/ItemDrawers#5]
when the player inventory is full, instead of dropping on the ground or not allowing retrieving a new stack, the next retrieved item simply gets deleted.

**Comment by war3i4i** [comment]
![image](https://github.com/war3i4i/ItemDrawers/assets/60820906/05d67cf4-29f9-43fe-9525-8a6ffd407905)
Just got stack of wood from drawer with full inventory and it appears under my character

**Comment by war3i4i** [comment]
Are you sure that drawer simply didn't pickup item back into itself? :D

**Comment by war3i4i** [comment]
In any case i've released 1.0.6 just now on Thunderstore in case items simply spawn under ground

**Comment by howardxu23** [comment]
spawning underground might be the issue tbh, as I can clearly see the item count going down but the item being nowhere to be seen

**Comment by war3i4i** [comment]
So is issue still there after 1.0.6?

**Comment by howardxu23** [comment]
All right, the item now drops at your feet when your inventory is full now
thanks!
