### ISSUE TITLE
Can't add arrows to item drawers

### ISSUE THREAD

**Issue by SavedByGrace251** [war3i4i/ItemDrawers#6]
When trying to select an arrow from the hot bar to put it in the drawer, it just equips the arrow rather then placing it in the drawer.

**Comment by war3i4i** [comment]
https://github.com/war3i4i/ItemDrawers/blob/f489c4d9fc8893e0dbf7adbd4fc6c28a5e5207cd/DrawerComponent.cs#L225C5-L225C5

Drawers can't accept Equipable items, such as arrows

**Comment by SavedByGrace251** [comment]
Is it possible to make this configurable? The original item drawers allowed for arrows at least to be store-able. Even if arrows were the only exception, it would be nice instead of just having to have a chest with a bunch of arrows dumped in it.

**Comment by war3i4i** [comment]
6bb2063

**Comment by SavedByGrace251** [comment]
Thunderstore hasn't updated with 1.0.7.  Is this version something I should download manually?

**Comment by war3i4i** [comment]
I will update mod in 2-3 days only, currently planing on small addition
