### ISSUE TITLE
Incompatible with "BetterArchery"

### ISSUE THREAD

**Issue by yepitsbrian** [war3i4i/ItemDrawers#9]
Removing items from storage drawers while using "BetterArchery" can cause the stack pulled from the drawer to disappear.

Replicate:
- Start world with "BetterArchery" and "ItemDrawers"
- Fill inventory slots with items
- Empty a slot in the numbered item slots (top row of inventory)
- Remove an item from a drawer (that can't stack with any items currently in inventory)

Item/stack of items will be subtracted from the drawer's inventory, but will disappear instead of spawning and falling to the ground.

**Comment by war3i4i** [comment]
That's something that should be written to BetterArchery mod dev. ItemDrawer item adding using vanilla methods so no problems from my side
